### ISSUE TITLE
`setup opsworks` incorrectly configures migrations

### ISSUE THREAD

**Issue by mfrister** [travis-ci/travis.rb#197]
Reproduce: Run `travis setup opsworks` and answer `yes` (or just press enter) when being asked "Migrate the database?".

The generated `.travis.yml` contains `migrate: true`, but within `deploy/on` instead of `deploy`:

``` yaml
deploy:
  provider: opsworks
  [...]
  on:
    migrate: true
    repo: ...
    [...]
```

The following would be correct according to the [docs](http://docs.travis-ci.com/user/deployment/opsworks/#Migrate-the-Database) and is the way that actually runs migrations.

``` yaml
deploy:
  provider: opsworks
  [...]
  migrate: true
  on:
    repo: ...
    [...]
```
