### ISSUE TITLE
`travis encrypt` only does one secure: per level

### ISSUE THREAD

**Issue by octylFractal** [travis-ci/travis.rb#208]
In the [docs](http://docs.travis-ci.com/user/encryption-keys/#Usage) it says that you can have multiple `secure: "...."` per area (`env`, `env.matrix`, etc.), but using the `--add` option with `travis encrypt` only allows one per level and removes anything that is not that one secure line.

Example:

``` yaml
env:
  - foo: "bar"
  - secure: .....somethingsecure
```

`travis encrypt 'BAR=FOO' --add env` ->

``` yaml
env:
  secure: .....a new secure string
```

Yes, it doesn't have any quotes.
