### ISSUE TITLE
Bug in config file

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis.rb#211]
It looks like there's some way for this to end up in the config file (a customer reported this):

``` YAML
last_check: {}
checked_completion: true
completion_version: 1.6.9
1.6.14 # this line
  at: 1404547583
checked_completion: true
completion_version: 1.6.9
```

This causes a YAML parse error. Not quite sure how it ended up in the config.
