### ISSUE TITLE
travis lint and multiple files in deploy

### ISSUE THREAD

**Issue by BlackEdder** [travis-ci/travis.rb#365]
When running travis lint on the a setup with multiple files in the deploy section I get the following error:

```
[x] in deploy section: dropping file section: unexpected sequence
```

This happens even when using it on one of the examples on the travis website:

```
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - "FILE 1"
    - "FILE 2"
  skip_cleanup: true
  on:
    tags: true
```
