### ISSUE TITLE
travis setup pypi adds "distributions" to deploy conditions

### ISSUE THREAD

**Issue by jthi3rry** [travis-ci/travis.rb#373]
`travis setup pypi` generates the following (`distributions` under `on`):

```
deploy:
  provider: pypi
  user: USERNAME
  password:
    secure: ENCRYPTED_PASSWORD
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: REPO
    branch: BRANCH
```

But should generate this instead (`distributions` under `deploy` as per https://docs.travis-ci.com/user/deployment/pypi#Uploading-different-distributions):

```
deploy:
  provider: pypi
  user: USERNAME
  password:
    secure: ENCRYPTED_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: REPO
    branch: BRANCH
```
