### ISSUE TITLE
travis lint generates bogus warnings on valid matrix.include keys

### ISSUE THREAD

**Issue by jhoblitt** [travis-ci/travis.rb#376]
This snippet of a `.travis.yml` file:

```
matrix:
  include:
    - rvm: '2.1'
      sudo: required
      services: docker
      env: PUPPET_VERSION="3.8.4" BEAKER_set="centos-6-docker"
      script: bundle exec rake acceptance
      bundler_args: --without development
```

Will generate these apparently bogus warnings:

```
Warnings for .travis.yml:
[x] in matrix.include section: unexpected key sudo, dropping
[x] in matrix.include section: unexpected key services, dropping
[x] in matrix.include section: unexpected key script, dropping
[x] in matrix.include section: unexpected key bundler_args, dropping
```
