### ISSUE TITLE
Linter contradicts docs, itself

### ISSUE THREAD

**Issue by kevinSuttle** [travis-ci/travis.rb#422]
``` bash
❯ travis --version
1.8.2

❯ travis lint .travis.yml
Warnings for .travis.yml:
[x] value for node_js section is empty, dropping
[x] in node_js section: value 6 is not a valid version
```

config:

``` yml
language: node_js
node_js:
  - "6"
script: npm test && npm run build:prod
```

Also tried to validate via linter:

``` yml
node_js:
  - 6

node_js:
  - '6'

# notice the lack of indentation 
node_js:
- "6"
```

https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions

> Use the following convenience versions:
> 
> `node` latest stable Node.js release
> `iojs` latest stable io.js release
> **`6`** latest 6.x release

**Comment by klaseskilson** [comment]
I am having similar issues. It seems the linter doesn't like sequences even though they are used in the docs. I get

```
Warnings for .travis.yml:
[x] in deploy section: dropping run section: unexpected sequence
```

when running `travis lint` on a .travis.yml from the [Heroku deployment example](https://docs.travis-ci.com/user/deployment/heroku/#Running-Commands):

```yml
deploy:
  provider: heroku
  api_key: ...
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
```

`travis --version` is `1.8.2` for me too. (It appears as if this has been a problem for quite some time now. https://github.com/travis-ci/travis-ci/issues/2368)

**Comment by robertpeteuil** [comment]
I have the same issue with sequences, and also the use of the `language` key in `matrix.include`.

```shell
> travis --version
1.8.8
> travis lint
Warnings for .travis.yml:
[x] in matrix.include.env section: does not support multiple values, dropping CACHE_NAME=JOB7
[x] in matrix.include section: unexpected key language, dropping
[x] in matrix.include.env section: does not support multiple values, dropping CACHE_NAME=JOB6
```

Here are the relevant lines in the `.travis.yml` file (which works fine by the way):

```yaml
matrix:
  include:
  - os: osx
    language: generic
    env:
    - BREW_PYTHON='python'
    - CACHE_NAME=JOB6
  - os: osx
    language: generic
    env:
    - BREW_PYTHON='python3'
    - CACHE_NAME=JOB7
```

**Comment by agraubert** [comment]
I'm also seeing similar warnings for the addons section:
```
$ travis lint
Warnings for .travis.yml:
[x] value for addons section is empty, dropping
[x] in addons section: unexpected key apt, dropping
```

Reference lines in my .travis.yml:
```yml
addons:
  apt:
    packages:
      - pandoc
```

**Comment by matatk** [comment]
I have the following relevant parts of `.travis.yml` (elided):

```yaml
addons:
  ssh_known_hosts:
    - . . .
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
```

I get the following output (similar to the post above):

```
Warnings for .travis.yml:
[x] in addons section: unexpected key apt, dropping
```

Seems like this is similar behaviour to the above post, and that it doesn't print the "empty" warning because we have some known hosts defined in there as well as the `apt` key.

**Comment by Kristinita** [comment]
+1. [**Similar issue for previous validation tool**](https://github.com/travis-ci/travis-yaml/issues/58).

Thanks.

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark: for me

### 1. Environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
1. travis 1.9.1
1. valid [**`.travis.yml`**](https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml)

    Example part of my `.travis.yml`:

    ```yaml
    addons:
      apt:
        packages:
        - apt-transport-https
        - parallel
        - xsltproc
    ```

### 2. Steps to reproduce

```text
travis lint -x
```

### 3. Behavior

```text
Hooray, .travis.yml looks valid :)
```

If I make intentional mistakes in my `.travis.yml` file, `travis lint` sees it.

Thanks.
