### ISSUE TITLE
Cloud Foundry login failing with unknown flag `u'

### ISSUE THREAD

**Issue by aemrie** [travis-ci/travis.rb#442]
```
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: ****
  password:
    secure: *********
  organization: ******
  space: *****
  on:
    branch: master
    repo: *****
```

> After correctly setting the API endpoint, Travis CI log states...
```
API endpoint: https://api.ng.bluemix.net (API version: 2.54.0)
Not logged in. Use 'cf login' to log in.
Incorrect Usage: unknown flag`u'
```
Username is simple email address that does not contain any special characters (Eg. user@***.com)
