### ISSUE TITLE
ElasticBeanstalk deployment fails (SSL_connect certificate verify failed (Seahorse::Client::NetworkingError))

### ISSUE THREAD

**Issue by lmenus** [travis-ci/travis.rb#660]
I am trying to deploy an application following [this guide](https://docs.travis-ci.com/user/deployment/elasticbeanstalk).

Here is the `.travis.yml` file.

```yml
addons:
  apt:
    packages:
      - libssl1.0.0

language: node_js
cache: npm

script:
 - npm test
 - npm run build

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: NBuJGJnRTlOes6Y6915xLrc4r3rG5+8l7Pj9Ah0WDyPQ3+HjvBv0Qeb5HuNx0IyI2fHfK85j9w78x3xdniXO2nUS1XviRcQ8fcTuvo0hKmTQcu1E/BATslJnNtRly4zDokFuwURPD326rA8mrjy1KM2Ty9kEatZLh8B4+TP08C74PnGgqH8xrzNjPzN6X6DHubGqCWI1Xq208M1zLT/vLxG+vOrz9WJg7KlOgdMN4jnZYa69jp/l3rBkosWCzwyQbqqspvKYfDsAMY1XioraDob62VAhxLg8S6+xmNlWC/sMOLFdGSg7mH4uS/BbR9wQq4smzlGf6e2xN5Lko3kp9TCHgz7VAmlBSfXJiWtEYWe+ZJ+OHQWWbiLIctQSSs8MIu+Jost/QuwADGkzXKkUAuhLDD3KQz65aeRaGVgtq1ham14mWcmJrRd5QglF2e94VtrOjveR71FXmk5AMmy8I2IE1KRji2OCJDv8p5MbWCSv4BnmhA63DKvi9is/F6sORN967D+Zw00tnqJxoe147jHOuy/kg4ekL10hvonP1SoJfpvNzyt/z8Q6Tt8Xit+0VhkBDeWbknxmNtgyUuIgVSST7CsE7Em99KbqWQ3tT/vc3Khby0qqJYWxn76aOcyMMGo1inRZ1uHiCw0sSB8zyRMiAQoXJz6wzLfN5l+t+YA=
  secret_access_key:
    secure: bxr1iFrT1pB1viXgmO+XT11a1iQssn//YyUkV6a7uLbkmFUmlwZIIQ+xZAYRXVfTMYKK6VLd21dSQaAexSTpwHVRtRyPmTWDgIh5wqnaj1D6f9dEzzk25l6BnSVvJVsVK+sRpA19cLgsV59q/HCf/D6eWs0vk9eYXzwMNorGSLVVVYS0f+LPPaJYTpKvER6USNKXgpFuUgyUNHrCzaqEqu8dd6jZYW3XYEKZ6HY/K3z4iUO5dAkWgZO7S9FasG+nwV1pTV1D4x580AjL/nGbPM3P/RRMMTZNC60RThkB4VePiHlcl77UgFzglfvbOwBt35WjCOujEEAVxbZABygSceoWPELEClYiu8IviUy+8qWeiVpWP7nehv97i8Y0QoUkvvCs4NfZyaknKBBU4n+wTRAvZq83CYoGnks3BqAPoAFu1stD+BG9eopX9t0JsMLea+SO1XMylL4N6pOKVQdFmoDuc0SVaTm2YZVTQ5bToMSkLe6Z4l8ZZULttJ2E1LKP3Z5EInBNIojb7LUlOG6wVqSLORAwSRs1k7PBA1t2E/w+aCHT9YqIaSuq91+a75ZOeV3bgvygBdVGWURGh0IxYPAUmtfSlEwc9LMoI3ZoilnpM1iar7fbaGzQRRzVwpLLCLX3qnwJ7ovMKU5xv7wVUl/l+oko2+ue3tqC10kBdQM=
  region: eu-west-1
  app: webapp-dev
  env: WECO
  bucket_name: travis-dev.weco.io
  on:
    branch: develop
```

And error log.

```sh
Deploying application
S3 client configured for "eu-west-1" but the bucket "travis-dev.weco.io" is in "eu-west-1"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts

/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Seahorse::Client::NetworkingError)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:882:in `start'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/net_http/handler.rb:119:in `session'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/net_http/handler.rb:45:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_host_id.rb:14:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:108:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/rest/handler.rb:7:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/poller.rb:61:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/poller.rb:47:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:104:in `block in poll'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-core-2.11.225/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-resources-2.11.225/lib/aws-sdk-resources/operations.rb:229:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-resources-2.11.225/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-resources-2.11.225/lib/aws-sdk-resources/resource.rb:131:in `exists?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-elastic_beanstalk-1.10.7/lib/dpl/provider/elastic_beanstalk.rb:101:in `bucket_exists?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-elastic_beanstalk-1.10.7/lib/dpl/provider/elastic_beanstalk.rb:41:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.7/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

Not sure what's going on there, but something about `client configured for "eu-west-1" but the bucket is in "eu-west-1"` does not sound right. It also seems that `travis setup elasticbeanstalk` is outdated as it does not ask for a required attribute `bucket_name`.
