### ISSUE TITLE
How to add a key on a list with --add?

### ISSUE THREAD

**Issue by yves-chevallier** [travis-ci/travis.rb#680]
I have the following: 

```yml
deploy:
   - provider: pypi
   - provider: releases
```

If I do it will refuse to add my password...

```
travis setup releases
```

If I try to add it manually with 

```
echo 'password' | travis encrypt --add deploy[1].password 
```

It also does not work :(
