### ISSUE TITLE
Lint leads to server error

### ISSUE THREAD

**Issue by k06a** [travis-ci/travis.rb#706]
Trying to validate:
```
travis lint ../.travis.yml
```
Getting:
```
server error (500: "Sorry, we experienced an error.\n\nrequest_id:5e9be46f-56c6-4471-a2a2-c169b02c560a\n")
```
Configuration:
>ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by ArthurFlageul** [comment]
Same problem with `1.8.11` and the previous version too.

**Comment by BanzaiMan** [comment]
Sorry, but I'm unable to reproduce the issue. If you are still experiencing this issue,

1. Point to the content of `.travis.yml` that you are trying to validate
1. Show the result of `travis report` immediately after the error message
1. Record the time (in UTC, please) when you experienced the error

Thanks.

**Comment by psafont** [comment]
```
$ travis report --pro && travis lint --pro --debug .travis.yml || true && date -u
System
Ruby:                     Ruby 2.6.5-p114
Operating System:         Fedora 31
RubyGems:                 RubyGems 3.0.3

CLI
Version:                  1.8.12
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-04-03 11:50:44 +0100

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "psafont"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
** Loading "/home/paus/.travis/config.yml"
** reading .travis.yml
** POST "lint" {"content"=>"language: c\nos: linux\ndist: xenial\ninstall:\n  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh\nscript: bash -ex .travis-opam.sh\nenv:\n  - OCAML_VERSION=4.02\n  - OCAML_VERSION=4.03\n  - OCAML_VERSION=4.04\n  - OCAML_VERSION=4.05\n  - OCAML_VERSION=4.06\n  - OCAML_VERSION=4.07\n  - OCAML_VERSION=4.08\n  - OCAML_VERSION=4.09\n  - OCAML_VERSION=4.10\n  global:\n  - secure: jgNNAbrODFH0dyZLrXD/zSI/U4luCwalj/Lqoz3IRMXwscshmIQDcp0KCghh6s65qCuMDlVjVwM8Kn+wftY40HRuuf+XA6hMpH8Jmbr4Qi3l5EnotLS4AH/GWhu/nP3F3MbaML+kUgg0GeH19qZ4npteefhDcONxw6xtvIR/6rg=\n  - PACKAGE=\"pci\"\n  - BISECT_ENABLE=yes\n\ndeploy:\n  provider: pages\n  skup_cleanup: true\n  github_token: $GITHUB_TOKEN\n  keep_history: true\n  on:\n    branch: master\n  target_branch: gh_pages\n"}
**   took 0.53 seconds
server error (500: "Sorry, we experienced an error.\n\nrequest_id:23a906bf-cd42-4ea6-b48f-b79749e72419\n")
Fri  3 Apr 10:51:43 UTC 2020
```

**Comment by BanzaiMan** [comment]
@psafont Your content has a YAML syntax error. We should be handling this more cleanly and alert you. You probably meant something like:

```yaml
language: c
os: linux
dist: xenial
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  jobs:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  global:
  - secure: jgNNAbrODFH0dyZLrXD/zSI/U4luCwalj/Lqoz3IRMXwscshmIQDcp0KCghh6s65qCuMDlVjVwM8Kn+wftY40HRuuf+XA6hMpH8Jmbr4Qi3l5EnotLS4AH/GWhu/nP3F3MbaML+kUgg0GeH19qZ4npteefhDcONxw6xtvIR/6rg=
  - PACKAGE="pci"
  - BISECT_ENABLE=yes

deploy:
  provider: pages
  skup_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  target_branch: gh_pages
```

Also try https://config.travis-ci.com/explore.
